# git-cliff configuration
# https://git-cliff.org/docs/configuration

[changelog]
header = """
# Changelog\n
All notable changes to this project will be documented in this file.\n
The format is based on [Keep a Changelog](https://keepachangelog.com/en/1.1.0/).\n
"""

body = """
{% if version %}\
    ## [{{ version }}] - {{ timestamp | date(format="%Y-%m-%d") }}
{% else %}\
    ## [unreleased]
{% endif %}\
{% for group, commits in commits | group_by(attribute="group") %}
### {{ group | upper_first }}
{% for commit in commits %}
- {{ commit.message | upper_first | trim }}\
{% if commit.remote.username %} by @{{ commit.remote.username }}{% endif %}\
{% if commit.remote.pr_number %} in #{{ commit.remote.pr_number }}{% endif %}
{% endfor %}
{% endfor %}
"""

trim = true
footer = ""

[git]
conventional_commits = false
filter_unconventional = false
split_commits = false
commit_preprocessors = [
  { pattern = '\n[\s\S]*', replace = "", replace_command = "" },
]
commit_parsers = [
  { message = "^feat", group = "Features" },
  { message = "^fix", group = "Bug Fixes" },
  { message = "^update", group = "Version Updates" },
  { message = "^clean up", group = "Cleanup" },
  { message = "^chore", group = "Chores" },
  { message = "^ci", group = "CI" },
  { message = "^doc", group = "Documentation" },
  { message = "^init", group = "Initial Commit" },
  { message = ".*", group = "Changes" },
]
protect_breaking_changes = false
filter_commits = false
tag_pattern = "v?[0-9].*"
sort_commits = "newest"
